image: php:8.1-fpm

cache:
  paths:
    - vendor/
    - composer.lock

before_script:
  # update system dependencies
  - apt-get update && apt-get install -y unzip
  # Install Composer
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install
  - php -v
  - composer -V

functions_tests:
  script:
    - ./vendor/bin/phpunit --testsuite functions